// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';
import 'package:space_news_aggregator/databases/objectbox_model.dart';
import 'package:space_news_aggregator/models/article_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 6820001789978745489),
      name: 'Favorite',
      lastPropertyId: const obx_int.IdUid(7, 3393354249006089005),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1267764006582449753),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8321852544856762573),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3319019456233634664),
            name: 'summary',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2233184681248218436),
            name: 'publishedDate',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5440871924318103870),
            name: 'source',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 9062129702169320036),
            name: 'url',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3393354249006089005),
            name: 'imageUrl',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 943990320432138347),
      name: 'Article',
      lastPropertyId: const obx_int.IdUid(8, 5260834159445884005),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4105180630664914853),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2236117056995274797),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2738846971329938468),
            name: 'summary',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2541875452090276313),
            name: 'publishedAt',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4459206365000100898),
            name: 'newsSite',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 9055981723911362348),
            name: 'source',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 7912572330356720396),
            name: 'url',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 5260834159445884005),
            name: 'imageUrl',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 943990320432138347),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Favorite: obx_int.EntityDefinition<Favorite>(
        model: _entities[0],
        toOneRelations: (Favorite object) => [],
        toManyRelations: (Favorite object) => {},
        getId: (Favorite object) => object.id,
        setId: (Favorite object, int id) {
          object.id = id;
        },
        objectToFB: (Favorite object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final summaryOffset = fbb.writeString(object.summary);
          final publishedDateOffset = fbb.writeString(object.publishedDate);
          final sourceOffset = fbb.writeString(object.source);
          final urlOffset = fbb.writeString(object.url);
          final imageUrlOffset = fbb.writeString(object.imageUrl);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, summaryOffset);
          fbb.addOffset(3, publishedDateOffset);
          fbb.addOffset(4, sourceOffset);
          fbb.addOffset(5, urlOffset);
          fbb.addOffset(6, imageUrlOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final summaryParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final publishedDateParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final sourceParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final urlParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final imageUrlParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final object = Favorite(
              id: idParam,
              title: titleParam,
              summary: summaryParam,
              publishedDate: publishedDateParam,
              source: sourceParam,
              url: urlParam,
              imageUrl: imageUrlParam);

          return object;
        }),
    Article: obx_int.EntityDefinition<Article>(
        model: _entities[1],
        toOneRelations: (Article object) => [],
        toManyRelations: (Article object) => {},
        getId: (Article object) => object.id,
        setId: (Article object, int id) {
          object.id = id;
        },
        objectToFB: (Article object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final summaryOffset = fbb.writeString(object.summary);
          final publishedAtOffset = fbb.writeString(object.publishedAt);
          final newsSiteOffset = fbb.writeString(object.newsSite);
          final sourceOffset = fbb.writeString(object.source);
          final urlOffset = fbb.writeString(object.url);
          final imageUrlOffset = fbb.writeString(object.imageUrl);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, summaryOffset);
          fbb.addOffset(3, publishedAtOffset);
          fbb.addOffset(4, newsSiteOffset);
          fbb.addOffset(5, sourceOffset);
          fbb.addOffset(6, urlOffset);
          fbb.addOffset(7, imageUrlOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final summaryParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final publishedAtParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final newsSiteParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final sourceParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final urlParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final imageUrlParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 18, '');
          final object = Article(
              id: idParam,
              title: titleParam,
              summary: summaryParam,
              publishedAt: publishedAtParam,
              newsSite: newsSiteParam,
              source: sourceParam,
              url: urlParam,
              imageUrl: imageUrlParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Favorite] entity fields to define ObjectBox queries.
class Favorite_ {
  /// See [Favorite.id].
  static final id =
      obx.QueryIntegerProperty<Favorite>(_entities[0].properties[0]);

  /// See [Favorite.title].
  static final title =
      obx.QueryStringProperty<Favorite>(_entities[0].properties[1]);

  /// See [Favorite.summary].
  static final summary =
      obx.QueryStringProperty<Favorite>(_entities[0].properties[2]);

  /// See [Favorite.publishedDate].
  static final publishedDate =
      obx.QueryStringProperty<Favorite>(_entities[0].properties[3]);

  /// See [Favorite.source].
  static final source =
      obx.QueryStringProperty<Favorite>(_entities[0].properties[4]);

  /// See [Favorite.url].
  static final url =
      obx.QueryStringProperty<Favorite>(_entities[0].properties[5]);

  /// See [Favorite.imageUrl].
  static final imageUrl =
      obx.QueryStringProperty<Favorite>(_entities[0].properties[6]);
}

/// [Article] entity fields to define ObjectBox queries.
class Article_ {
  /// See [Article.id].
  static final id =
      obx.QueryIntegerProperty<Article>(_entities[1].properties[0]);

  /// See [Article.title].
  static final title =
      obx.QueryStringProperty<Article>(_entities[1].properties[1]);

  /// See [Article.summary].
  static final summary =
      obx.QueryStringProperty<Article>(_entities[1].properties[2]);

  /// See [Article.publishedAt].
  static final publishedAt =
      obx.QueryStringProperty<Article>(_entities[1].properties[3]);

  /// See [Article.newsSite].
  static final newsSite =
      obx.QueryStringProperty<Article>(_entities[1].properties[4]);

  /// See [Article.source].
  static final source =
      obx.QueryStringProperty<Article>(_entities[1].properties[5]);

  /// See [Article.url].
  static final url =
      obx.QueryStringProperty<Article>(_entities[1].properties[6]);

  /// See [Article.imageUrl].
  static final imageUrl =
      obx.QueryStringProperty<Article>(_entities[1].properties[7]);
}
